language: go

go:
  - 1.11.0

script:
  - make test-all
  - make dist

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: _dist/helm-monitor*
    skip_cleanup: true
    file_glob: true
    on:
      tags: true
