---
name: "monitor"
version: "0.4.0"
usage: "monitor and rollback in case of failure based on metrics or logs"
description: |-
  Query at a given interval a Prometheus, Elasticsearch or Sentry instance. A
  rollback of the release is initiated if the number of result is positive.
ignoreFlags: false
useTunnel: true
command: "$HELM_PLUGIN_DIR/helm-monitor"
hooks:
  install: "$HELM_PLUGIN_DIR/install.sh"
