---
name: "monitor"
version: "0.1.0"
usage: "monitor and rollback in case of failure based on metrics or logs"
description: |-
  Query at a given interval a Prometheus or ElasticSearch instance, a rollback
  of the release is initiated if the number of item from the result is positive.
ignoreFlags: false
useTunnel: true
command: "$HELM_PLUGIN_DIR/helm-monitor"
hooks:
  install: "$HELM_PLUGIN_DIR/install.sh"
